/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => HTMLPreviewPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian3 = require("obsidian");

// src/HTMLPreviewProcessor.ts
var import_obsidian2 = require("obsidian");

// src/IframeBridge.ts
var HEIGHT_REPORTER_ID = "html-preview-height-reporter";
function getHeightReporterSource() {
  return `
(function() {
	var fallbackTimer;
	function reportHeight() {
		var h = Math.max(document.documentElement.scrollHeight, document.body ? document.body.scrollHeight : 0);
		if (h > 0) {
			parent.postMessage({ type: "html-preview-height", height: h }, "*");
		}
	}
	window.addEventListener("load", function() {
		reportHeight();
		if (typeof ResizeObserver === "function") {
			var observer = new ResizeObserver(reportHeight);
			observer.observe(document.body);
			if (document.documentElement !== document.body) {
				observer.observe(document.documentElement);
			}
			window.addEventListener("unload", function() { observer.disconnect(); }, { once: true });
		} else {
			fallbackTimer = window.setInterval(reportHeight, 500);
			window.setTimeout(function() { window.clearInterval(fallbackTimer); }, 10000);
		}
	});
})();
`;
}
function isHeightMessage(data) {
  if (typeof data !== "object" || data === null) return false;
  const candidate = data;
  return candidate.type === "html-preview-height" && typeof candidate.height === "number" && Number.isFinite(candidate.height);
}
function registerHeightHandler(iframe, handler) {
  const listener = (event) => {
    if (event.source !== iframe.contentWindow || !isHeightMessage(event.data)) return;
    handler(event.data.height);
  };
  window.addEventListener("message", listener);
  return () => {
    window.removeEventListener("message", listener);
  };
}

// src/DocumentBuilder.ts
var PREVIEW_STYLE_ID = "html-preview-base-styles";
var PREVIEW_STYLES = `
*,*::before,*::after{box-sizing:border-box}
html,body{overflow-x:hidden;scrollbar-width:none;-ms-overflow-style:none}
body{margin:0;padding:8px;font-family:var(--font-text,sans-serif);background:transparent;color:var(--text-normal,#ccc)}
a{color:var(--text-accent,#7c5cbf)}
::-webkit-scrollbar{width:0;height:0}
`;
function buildPreviewDocument(source) {
  var _a, _b;
  const document = new DOMParser().parseFromString(source, "text/html");
  const existingCharset = document.head.querySelector("meta[charset]");
  if (existingCharset) {
    existingCharset.setAttribute("charset", "utf-8");
  } else {
    const charset = document.createElement("meta");
    charset.setAttribute("charset", "utf-8");
    document.head.prepend(charset);
  }
  if (!document.head.querySelector('meta[name="viewport" i]')) {
    const viewport = document.createElement("meta");
    viewport.name = "viewport";
    viewport.content = "width=device-width, initial-scale=1.0";
    document.head.append(viewport);
  }
  (_a = document.getElementById(PREVIEW_STYLE_ID)) == null ? void 0 : _a.remove();
  const style = document.createElement("style");
  style.id = PREVIEW_STYLE_ID;
  style.textContent = PREVIEW_STYLES;
  document.head.append(style);
  (_b = document.getElementById(HEIGHT_REPORTER_ID)) == null ? void 0 : _b.remove();
  const reporter = document.createElement("script");
  reporter.id = HEIGHT_REPORTER_ID;
  reporter.textContent = getHeightReporterSource();
  document.body.append(reporter);
  return `<!doctype html>
${document.documentElement.outerHTML}`;
}

// src/PreviewSizing.ts
var MIN_PREVIEW_HEIGHT = 50;
var MAX_PREVIEW_HEIGHT = 2e3;
function clampHeight(height) {
  return Math.min(Math.max(height, MIN_PREVIEW_HEIGHT), MAX_PREVIEW_HEIGHT);
}
function applyHeight(iframe, height) {
  if (!Number.isFinite(height) || height <= 0) return;
  iframe.style.height = `${clampHeight(height)}px`;
}
function getDefaultHeight(config) {
  return clampHeight(config.defaultHeight);
}

// src/Toolbar.ts
var import_obsidian = require("obsidian");
function createButton(parent, icon, label, onClick, disposers) {
  const button = parent.createEl("button", {
    cls: "clickable-icon html-preview-toolbar-btn",
    attr: { "aria-label": label, title: label, type: "button" }
  });
  (0, import_obsidian.setIcon)(button, icon);
  button.addEventListener("click", onClick);
  disposers.push(() => button.removeEventListener("click", onClick));
  return button;
}
function createToolbar(parentEl, initialMode, callbacks) {
  const toolbar = parentEl.createDiv({ cls: "html-preview-toolbar" });
  const buttons = toolbar.createDiv({ cls: "html-preview-toolbar-btns" });
  const disposers = [];
  createButton(buttons, "refresh-cw", "Refresh preview", callbacks.onRefresh, disposers);
  createButton(buttons, "maximize-2", "Fullscreen preview", callbacks.onFullscreen, disposers);
  let feedbackTimer;
  const copyButton = createButton(buttons, "copy", "Copy HTML source", () => {
    void navigator.clipboard.writeText(callbacks.getSource()).then(() => {
      copyButton.addClass("html-preview-copied");
      window.clearTimeout(feedbackTimer);
      feedbackTimer = window.setTimeout(() => {
        copyButton.removeClass("html-preview-copied");
      }, 1200);
    }).catch(() => {
      new import_obsidian.Notice("Could not copy HTML source");
    });
  }, disposers);
  let mode = initialMode;
  const sizeButton = createButton(buttons, "scan", "Auto sizing (click for manual)", () => {
    callbacks.onSizingModeChange(mode === "auto" ? "manual" : "auto");
  }, disposers);
  const setSizingMode = (nextMode) => {
    mode = nextMode;
    const auto = mode === "auto";
    const label = auto ? "Auto sizing (click for manual)" : "Manual sizing (click for auto)";
    sizeButton.empty();
    (0, import_obsidian.setIcon)(sizeButton, auto ? "scan" : "move-vertical");
    sizeButton.setAttribute("aria-label", label);
    sizeButton.title = label;
  };
  setSizingMode(initialMode);
  return {
    setSizingMode,
    dispose: () => {
      window.clearTimeout(feedbackTimer);
      for (const dispose of disposers) dispose();
    }
  };
}

// src/types.ts
var DEFAULT_CONFIG = {
  autoHeight: true,
  defaultHeight: 300
};

// src/HTMLPreviewProcessor.ts
function createPreview(parentEl, source, app, config = DEFAULT_CONFIG) {
  const wrapper = parentEl.createDiv({ cls: "html-preview-container" });
  let mode = config.autoHeight ? "auto" : "manual";
  let manualHeight = getDefaultHeight(config);
  let lastReportedHeight = 0;
  let disposed = false;
  let iframe;
  const setSizingMode = (nextMode) => {
    mode = nextMode;
    wrapper.dataset.sizing = mode;
    toolbar.setSizingMode(mode);
    if (mode === "manual") {
      manualHeight = clampHeight(iframe.offsetHeight || manualHeight);
      applyHeight(iframe, manualHeight);
    } else if (lastReportedHeight > 0) {
      applyHeight(iframe, lastReportedHeight);
    }
  };
  const refresh = () => {
    if (disposed) return;
    iframe.srcdoc = buildPreviewDocument(source);
    if (mode === "manual") applyHeight(iframe, manualHeight);
  };
  const toolbar = createToolbar(wrapper, mode, {
    onRefresh: refresh,
    onFullscreen: () => new HTMLPreviewModal(app, source).open(),
    onSizingModeChange: setSizingMode,
    getSource: () => source
  });
  iframe = wrapper.createEl("iframe", {
    cls: "html-preview-iframe",
    attr: {
      sandbox: "allow-scripts allow-forms",
      loading: "lazy",
      title: "HTML preview"
    }
  });
  const resizeHandle = wrapper.createDiv({
    cls: "html-preview-resize-handle",
    attr: { "aria-hidden": "true" }
  });
  setSizingMode(mode);
  const unregisterHeightHandler = registerHeightHandler(iframe, (height) => {
    lastReportedHeight = clampHeight(height);
    if (mode === "auto") applyHeight(iframe, lastReportedHeight);
  });
  let activePointerId = null;
  let startY = 0;
  let startHeight = 0;
  const stopResize = () => {
    activePointerId = null;
    window.removeEventListener("pointermove", onPointerMove);
    window.removeEventListener("pointerup", stopResize);
    window.removeEventListener("pointercancel", stopResize);
  };
  const onPointerMove = (event) => {
    if (activePointerId !== event.pointerId) return;
    manualHeight = clampHeight(startHeight + event.clientY - startY);
    applyHeight(iframe, manualHeight);
  };
  const onPointerDown = (event) => {
    if (mode !== "manual" || activePointerId !== null) return;
    event.preventDefault();
    activePointerId = event.pointerId;
    startY = event.clientY;
    startHeight = iframe.offsetHeight;
    window.addEventListener("pointermove", onPointerMove);
    window.addEventListener("pointerup", stopResize);
    window.addEventListener("pointercancel", stopResize);
  };
  resizeHandle.addEventListener("pointerdown", onPointerDown);
  refresh();
  return {
    refresh,
    dispose: () => {
      if (disposed) return;
      disposed = true;
      stopResize();
      resizeHandle.removeEventListener("pointerdown", onPointerDown);
      unregisterHeightHandler();
      toolbar.dispose();
    }
  };
}
var HTMLPreviewModal = class extends import_obsidian2.Modal {
  constructor(app, html) {
    super(app);
    this.html = html;
  }
  onOpen() {
    this.contentEl.addClass("html-preview-modal-content");
    const iframe = this.contentEl.createEl("iframe", {
      cls: "html-preview-modal-iframe",
      attr: {
        sandbox: "allow-scripts allow-forms",
        title: "Fullscreen HTML preview"
      }
    });
    iframe.srcdoc = buildPreviewDocument(this.html);
    this.cleanup = registerHeightHandler(iframe, (height) => {
      const maxHeight = Math.max(window.innerHeight - 80, 100);
      iframe.style.height = `${Math.min(clampHeight(height), maxHeight)}px`;
    });
  }
  onClose() {
    var _a;
    (_a = this.cleanup) == null ? void 0 : _a.call(this);
    this.cleanup = void 0;
    this.contentEl.empty();
  }
};

// src/PreviewRegistry.ts
var PreviewRegistry = class {
  constructor() {
    this.previews = /* @__PURE__ */ new Set();
  }
  add(preview) {
    this.previews.add(preview);
    return () => this.previews.delete(preview);
  }
  refreshAll() {
    for (const preview of this.previews) preview.refresh();
  }
  disposeAll() {
    for (const preview of this.previews) preview.dispose();
    this.previews.clear();
  }
};

// src/main.ts
var PreviewRenderChild = class extends import_obsidian3.MarkdownRenderChild {
  constructor(containerEl, controller, onDispose) {
    super(containerEl);
    this.controller = controller;
    this.onDispose = onDispose;
  }
  onunload() {
    this.controller.dispose();
    this.onDispose();
  }
};
var HTMLPreviewPlugin = class extends import_obsidian3.Plugin {
  constructor() {
    super(...arguments);
    this.previews = new PreviewRegistry();
  }
  onload() {
    this.registerMarkdownCodeBlockProcessor("html-preview", (source, el, ctx) => {
      const preview = createPreview(el, source, this.app);
      ctx.addChild(new PreviewRenderChild(el, preview, this.previews.add(preview)));
    });
    this.addCommand({
      id: "refresh-html-previews",
      name: "Refresh all HTML previews",
      callback: () => this.previews.refreshAll()
    });
  }
  onunload() {
    this.previews.disposeAll();
  }
};
